AllCops:
  Exclude:
    - 'bin/**'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Detect:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$progress]

Style/GuardClause:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SpaceAroundOperators:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Alias:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Lint/LiteralInCondition:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Enabled: false
