defaults: &defaults
  # perforce:
  #   port: "localhost:1666"
  #   user: "jdoe"
  #   password: "secret"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
