# Linter Documentation:
# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

scss_files: 'app/assets/stylesheets/**/*.scss'

exclude:
  - 'app/assets/stylesheets/pages/emojis.scss'

linters:
  BangFormat:
    enabled: false
  
  BorderZero:
    enabled: false
  
  ColorKeyword:
    enabled: false
  
  ColorVariable:
    enabled: false
  
  Comment:
    enabled: false
  
  DeclarationOrder:
    enabled: false

  # `scss-lint:disable` control comments should be preceded by a comment
  # explaining why these linters are being disabled for this file.
  # See https://github.com/brigade/scss-lint#disabling-linters-via-source for
  # more information.
  DisableLinterReason:
    enabled: true
  
  DuplicateProperty:
    enabled: false
  
  EmptyLineBetweenBlocks:
    enabled: false
  
  EmptyRule:
    enabled: false
  
  FinalNewline:
    enabled: false
  
  # HEX colors should use three-character values where possible.
  HexLength:
    enabled: true
  
  # HEX color values should use lower-case colors to differentiate between
  # letters and numbers, e.g. `#E3E3E3` vs. `#e3e3e3`.
  HexNotation:
    enabled: true
  
  IdSelector:
    enabled: false
  
  ImportPath:
    enabled: false
  
  ImportantRule:
    enabled: false
  
  # Indentation should always be done in increments of 2 spaces.
  Indentation:
    enabled: true
    width: 2
  
  LeadingZero:
    enabled: false
  
  MergeableSelector:
    enabled: false
  
  NameFormat:
    enabled: false
  
  NestingDepth:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false
  
  PropertySpelling:
    enabled: false
  
  PseudoElement:
    enabled: false
  
  QualifyingElement:
    enabled: false
  
  SelectorDepth:
    enabled: false
  
  # Selectors should always use hyphenated-lowercase, rather than camelCase or
  # snake_case.
  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase
  
  # Prefer the shortest shorthand form possible for properties that support it.
  Shorthand:
    enabled: true
  
  # Each property should have its own line, except in the special case of
  # single line rulesets.
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: false
  
  SpaceAfterComma:
    enabled: false
  
  # Properties should be formatted with a single space separating the colon
  # from the property's value.
  SpaceAfterPropertyColon:
    enabled: true

  # Properties should be formatted with no space between the name and the
  # colon.
  SpaceAfterPropertyName:
    enabled: true
  
  SpaceAroundOperator:
    enabled: false
  
  SpaceBeforeBrace:
    enabled: false
  
  StringQuotes:
    enabled: false

  TrailingSemicolon:
    enabled: false

  TrailingWhitespace:
    enabled: false

  UnnecessaryMantissa:
    enabled: false

  UnnecessaryParentReference:
    enabled: false

  VendorPrefix:
    enabled: false

  # Omit length units on zero values, e.g. `0px` vs. `0`.
  ZeroUnit:
    enabled: true
