require 'perforce_swarm/active_support/concern'
require 'perforce_swarm/engine'
require 'perforce_swarm/haml'
autoload(:Spinach, 'perforce_swarm/spinach') if ENV['RAILS_ENV'] == 'test'
autoload(:RSpec,  'perforce_swarm/rspec') if ENV['RAILS_ENV'] == 'test'
