# Here is a list of jobs that are scheduled to run periodically.
# We use a UNIX cron notation to specify execution schedule.
#
# Please read here for more information:
# https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job

stuck_ci_builds_worker:
  cron: "0 0 * * *"
  class: "StuckCiBuildsWorker"
  queue: "default"
