# Configuration properties for validation tests

gitswarm_url : http://10.2.0.108/
gitswarm_username : root
gitswarm_password : 5iveL!fe

p4_port : ssl:10.2.0.108:1666
p4_user : root
p4_password : 5iveL!fe
p4_gitswarm_depot_root : //gitswarm/projects/

git_binary : git