#!/usr/bin/env rake
require 'rake'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:test) do |t|
  t.pattern = Dir.glob('spec/**/*_spec.rb')
  t.rspec_opts = '--format documentation'
end

RSpec::Core::RakeTask.new(:testPasswordSync) do |t|
  t.pattern = Dir.glob('spec/**/*_spec.rb')
  t.rspec_opts = '--format documentation --tag @PasswordSync'
end

RSpec::Core::RakeTask.new(:testMirroring) do |t|
  t.pattern = Dir.glob('spec/**/*_spec.rb')
  t.rspec_opts = '--format documentation --tag @Mirroring'
end

RSpec::Core::RakeTask.new(:testEnforcePermission) do |t|
  t.pattern = Dir.glob('spec/**/*_spec.rb')
  t.rspec_opts = '--format documentation --tag @EnforcePermission'
end

task(default: :test)
